### ISSUE TITLE
Will Not Compile on Linux 7.2+

### ISSUE THREAD

**Issue by HurricanePootis** [ASIXElectronics/asix-usb-nic-linux-driver#1]
Hello,

I am trying to compile 4.1.0 on Linux 7.2.3. I get the following error:

```
hurricane@TheCloutPC ~/asix-usb-nic-linux-driver $ make
make -C /lib/modules/7.2.3-zen1-3-zen/build M=/home/hurricane/asix-usb-nic-linux-driver modules
make[1]: Entering directory '/usr/lib/modules/7.2.3-zen1-3-zen/build'
make[2]: Entering directory '/home/hurricane/asix-usb-nic-linux-driver'
  CC [M]  ax_main.o
  CC [M]  ax88179_178a.o
  CC [M]  ax88179a_772d.o
  CC [M]  ax_ptp.o
ax88179_178a.c: In function ‘ax88179_signature’:
ax88179_178a.c:110:9: error: implicit declaration of function ‘strncpy’ [-Wimplicit-function-declaration]
  110 |         strncpy(info->sig, AX88179_SIGNATURE, strlen(AX88179_SIGNATURE));
      |         ^~~~~~~
ax88179_178a.c:19:1: note: include ‘<string.h>’ or provide a declaration of ‘strncpy’
   18 | #include "ax88179_178a.h"
  +++ |+#include <string.h>
   19 | 
ax88179_178a.c:110:9: warning: incompatible implicit declaration of built-in function ‘strncpy’ [-Wbuiltin-declaration-mismatch]
  110 |         strncpy(info->sig, AX88179_SIGNATURE, strlen(AX88179_SIGNATURE));
      |         ^~~~~~~
ax88179_178a.c:110:9: note: include ‘<string.h>’ or provide a declaration of ‘strncpy’
ax88179a_772d.c: In function ‘ax88179a_signature’:
ax88179a_772d.c:615:17: error: implicit declaration of function ‘strncpy’ [-Wimplicit-function-declaration]
  615 |                 strncpy(info->sig, AX88279A_SIGNATURE, strlen(AX88279A_SIGNATURE));
      |                 ^~~~~~~
ax88179a_772d.c:19:1: note: include ‘<string.h>’ or provide a declaration of ‘strncpy’
   18 | #include "ax88179a_772d.h"
  +++ |+#include <string.h>
   19 | #ifdef ENABLE_PTP_FUNC
ax88179a_772d.c:615:17: warning: incompatible implicit declaration of built-in function ‘strncpy’ [-Wbuiltin-declaration-mismatch]
  615 |                 strncpy(info->sig, AX88279A_SIGNATURE, strlen(AX88279A_SIGNATURE));
      |                 ^~~~~~~
ax88179a_772d.c:615:17: note: include ‘<string.h>’ or provide a declaration of ‘strncpy’
ax88179a_772d.c:617:17: warning: incompatible implicit declaration of built-in function ‘strncpy’ [-Wbuiltin-declaration-mismatch]
  617 |                 strncpy(info->sig, AX88179A_SIGNATURE, strlen(AX88179A_SIGNATURE));
      |                 ^~~~~~~
ax88179a_772d.c:617:17: note: include ‘<string.h>’ or provide a declaration of ‘strncpy’
make[4]: *** [/usr/lib/modules/7.2.3-zen1-3-zen/build/scripts/Makefile.build:289: ax88179_178a.o] Error 1
make[4]: *** Waiting for unfinished jobs....
make[4]: *** [/usr/lib/modules/7.2.3-zen1-3-zen/build/scripts/Makefile.build:289: ax88179a_772d.o] Error 1
make[3]: *** [/usr/lib/modules/7.2.3-zen1-3-zen/build/Makefile:2190: .] Error 2
make[2]: *** [/usr/lib/modules/7.2.3-zen1-3-zen/build/Makefile:248: __sub-make] Error 2
make[2]: Leaving directory '/home/hurricane/asix-usb-nic-linux-driver'
make[1]: *** [Makefile:248: __sub-make] Error 2
make[1]: Leaving directory '/usr/lib/modules/7.2.3-zen1-3-zen/build'
make: *** [Makefile:24: all] Error 2
```

According to [this article](https://www.phoronix.com/news/Linux-7.2-Drops-strncpy), Linux has eliminated the strncpy API in Linux 7.2. According to the article,
> In place of strncpy, Linux kernel code should use strscpy() for NUL terminated destinations, strscpy_pad() for NUl-terminated destinations with zero-> padding, strtomem_pad() for non-NUL-terminated fixed-width fields, memcpy_and_pad() for bounded copies with explicit padding, or memcpy() for > known-length memory copies.
